config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  #/login, /logout
  devise_for :users, :path => "/", :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:sessions => "sessions"}
  #/login, /logout

  get '404', :to => 'application#page_not_found', as: :no_route

  #manager
  namespace :manager do
    get 'calculations' => 'calculations#index'
    scope :calculation do
      get 'new' => 'calculation#new', as: :new_calculation
      post '/' => 'calculation#create', as: :create_calculation
      get ':id' => 'calculation#edit', as: :edit_calculation
      post ':id' => 'calculation#save', as: :save_calculation
    end

    scope :variable do
      match ':id' => 'variable#show', as: :variable, via: [:get, :post]
    end

    scope :multiple do
      get ':id' => 'multiple#new', as: :new_multiple
      post ':id' => 'multiple#create', as: :create_multiple
    end

    get 'api/density/:id' => 'api#density', as: :api_density
    get 'api/layout' => 'api#layout', as: :api_layout

    get 'clients' => 'clients#index'
    scope :client do
      get 'new' => 'client#new', as: :new_client
      post '/' => 'client#create', as: :create_client
      delete ':id' => 'client#destroy', as: :destroy_client
      get ':id' => 'client#edit', as: :edit_client
      post ':id' => 'client#update', as: :update_client

      get ':id/branches' => 'branches#index', as: :branches
      scope ':id/branch' do
        get 'new' => 'branch#new', as: :new_branch
        post '/' => 'branch#create', as: :create_branch
      end

      get ':id/specifications' => 'specifications#index', as: :specifications
      scope ':id/specification' do
        get 'new' => 'specification#new', as: :new_specification
        post '/' => 'specification#create', as: :create_specification
      end

      get ':id/transfered_specifications' => 'transfered_specifications#index', as: :transfered_specifications
      get ':id/transfered_branches' => 'transfered_branches#index', as: :transfered_branches
    end

    scope 'branch' do
      delete ':id' => 'branch#destroy', as: :destroy_branch
      get ':id' => 'branch#edit', as: :edit_branch
      post ':id' => 'branch#update', as: :update_branch
    end

    scope 'specification' do
      delete ':id' => 'specification#destroy', as: :destroy_specification
      get ':id' => 'specification#edit', as: :edit_specification
      post ':id' => 'specification#update', as: :update_specification
    end

    get 'transfered_clients' => 'transfered_clients#index'
    scope :transfered_client do
      post '/' => 'application#page_not_found'
      post ':id' => 'transfered_client#update', as: :update_transfered_client
    end

    scope 'transfered_specification' do
      post ':id' => 'transfered_specification#update', as: :update_transfered_specification
      get ':id' => 'transfered_specification#edit', as: :edit_transfered_specification
    end

    scope 'transfered_branch' do
      post ':id' => 'transfered_branch#update', as: :update_transfered_branch
      get ':id' => 'transfered_branch#edit', as: :edit_transfered_branch
    end
  end
  #manager - end

  #admin
  get 'product_paddings', :to => 'admin/product_paddings#index'
  resource :product_padding, :only => [] do
    get ':id' => 'admin/product_padding#edit', :as => :edit
    post ':id' => 'admin/product_padding#update', :as => :update
  end

  get 'additionals', :to => 'admin/additionals#index'
  resource :additional, :only => [] do
    get ':id' => 'admin/additional#edit', :as => :edit
    post ':id' => 'admin/additional#update', :as => :update
  end

  get 'uv_polish_prices', :to => 'admin/uv_polish_prices#index'
  resource :uv_polish_price, :only => [] do
    get ':id' => 'admin/uv_polish_price#edit', as: :edit
    post ':id' => 'admin/uv_polish_price#update', as: :update
  end

  get 'currencies', :to => 'admin/currencies#index'
  resource :currency, :only => [] do
    get ':id' => 'admin/currency#edit', :as => :edit
    post ':id' => 'admin/currency#update', :as => :update
  end

  get 'products', :to => 'admin/products#index'
  resource :product, :only => [] do
    get 'new' => 'admin/product#new', :as => :new
    post '/' => 'admin/product#create', :as => :create
    delete ':id' => 'admin/product#destroy', :as => :destroy
    get ':id' => 'admin/product#edit', :as => :edit
    post ':id' => 'admin/product#update', :as => :update
  end

  get 'clients', :to => 'admin/clients#index'
  resource :client, :only => [] do
    get 'new' => 'admin/client#new', :as => :new
    post '/' => 'admin/client#create', :as => :create
    delete ':id' => 'admin/client#destroy', :as => :destroy
    get ':id' => 'admin/client#edit', :as => :edit
    post ':id' => 'admin/client#update', :as => :update
    get ':id/branches' => 'admin/branches#index', :as => :branches
  end

  #branch
  get 'client/:id/branch/new' => 'admin/branch#new', :as => :new_branch
  post 'client/:id/branch' => 'admin/branch#create', :as => :create_branch
  resource :branch, :only => [] do
    delete ':id' => 'admin/branch#destroy', :as => :destroy
    get ':id' => 'admin/branch#edit', :as => :edit
    post ':id' => 'admin/branch#update', :as => :update
  end

  get 'managers', :to => 'admin/managers#index'
  resource :manager, :only => [] do
    get 'new' => 'admin/manager#new', :as => :new
    post '/' => 'admin/manager#create', :as => :create
    delete ':id' => 'admin/manager#destroy', :as => :destroy
    post ':id/block' => 'admin/manager#block', :as => :block
    post ':id/unblock' => 'admin/manager#unblock', :as => :unblock
    get ':id' => 'admin/manager#edit', :as => :edit
    post ':id' => 'admin/manager#update', :as => :update
  end

  get 'papers', :to => 'admin/papers#index'
  resource :paper, :only => [] do
    get 'new' => 'admin/paper#new', :as => :new
    post '/' => 'admin/paper#create', :as => :create
    delete ':id' => 'admin/paper#destroy', :as => :destroy
    get ':id' => 'admin/paper#edit', :as => :edit
    post ':id' => 'admin/paper#update', :as => :update
    get ':id/features' => 'admin/features#index', :as => :features
  end

  get 'machines', :to => 'admin/machines#index'
  resource :machine, :only => [] do
    get 'new' => 'admin/machine#new', :as => :new
    post '/' => 'admin/machine#create', :as => :create
    delete ':id' => 'admin/machine#destroy', :as => :destroy
    get ':id' => 'admin/machine#edit', :as => :edit
    post ':id' => 'admin/machine#update', :as => :update
  end

  get 'materials', :to => 'admin/materials#index'
  resource :material, :only => [] do
    get 'new' => 'admin/material#new', :as => :new
    post '/' => 'admin/material#create', :as => :create
    delete ':id' => 'admin/material#destroy', :as => :destroy
    get ':id' => 'admin/material#edit', :as => :edit
    post ':id' => 'admin/material#update', :as => :update
  end

  get 'cover_work_types', :to => 'admin/cover_work_types#index'
  resource :cover_work_type, :only => [] do
    get 'new' => 'admin/cover_work_type#new', :as => :new
    post '/' => 'admin/cover_work_type#create', :as => :create
    delete ':id' => 'admin/cover_work_type#destroy', :as => :destroy
    get ':id' => 'admin/cover_work_type#edit', :as => :edit
    post ':id' => 'admin/cover_work_type#update', :as => :update
  end

  get 'paper/:id/feature/new' => 'admin/feature#new', :as => :new_feature
  post 'paper/:id/feature' => 'admin/feature#create', :as => :create_feature
  resource :feature, :only => [] do
    delete ':id' => 'admin/feature#destroy', :as => :destroy
    get ':id' => 'admin/feature#edit', :as => :edit
    post ':id' => 'admin/feature#update', :as => :update
    get ':id/clone' => 'admin/feature#clone', :as => :clone
    get ':id/cuts' => 'admin/cuts#index', :as => :cuts
  end

  #cut
  get 'feature/:id/cut/new' => 'admin/cut#new', :as => :new_cut
  post 'feature/:id/cut' => 'admin/cut#create', :as => :create_cut
  resource :cut, :only => [] do
    delete ':id' => 'admin/cut#destroy', :as => :destroy
    get ':id' => 'admin/cut#edit', :as => :edit
    post ':id' => 'admin/cut#update', :as => :update
  end

  get 'discounts', :to => 'admin/discounts#index'
  resource :discount, :only => [] do
    get 'new' => 'admin/discount#new', :as => :new
    post '/' => 'admin/discount#create', :as => :create
    delete ':id' => 'admin/discount#destroy', :as => :destroy
    get ':id' => 'admin/discount#edit', :as => :edit
    post ':id' => 'admin/discount#update', :as => :update
  end
  #admin - end

  #root
  root :to => 'root#index'
  #root - end

end

app/models/client.rb
# -*- encoding : utf-8 -*-
class Client < ActiveRecord::Base
  validates :fio, :discount_id, :manager_id, :contract_status_id, :'client/not_blank' => true

  belongs_to :manager, class_name: 'User'
  has_many :calculations
  belongs_to :discount
  has_many :branches
  belongs_to :contract_status
  has_many :specifications

  def manager
    return super if super.present?
    User.admin
  end

end

app/controllers/admin/client_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ClientController < Admin::ApplicationController

  before_action :find_client!, only: [:destroy, :edit, :update]

  def create
    new_client = Client.new

    new_client.fio = client_params[:fio]
    new_client.phone = client_params[:phone]
    new_client.email = client_params[:email]
    new_client.contract = client_params[:contract]
    new_client.payer = client_params[:payer]
    new_client.description = client_params[:description]
    new_client.manager = User.find_by(id: client_params[:manager])
    new_client.discount = Discount.find_by(id: client_params[:discount])
    new_client.shipping_address = client_params[:shipping_address]
    new_client.contract_status = ContractStatus.find_by(id: client_params[:contract_status])

    if new_client.save
      flash[:notice] = I18n.t('client.success.created')
      path = clients_path
    else
      flash[:alert] = new_client.errors.full_messages
      path = new_client_path
    end

    redirect_to path
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: I18n.t('client.success.deleted')
  end

  def update
    @client.fio = client_params[:fio]
    @client.phone = client_params[:phone]
    @client.email = client_params[:email]
    @client.contract = client_params[:contract]
    @client.payer = client_params[:payer]
    @client.description = client_params[:description]
    @client.manager = User.find_by(id: client_params[:manager])
    @client.discount = Discount.find_by(id: client_params[:discount])
    @client.shipping_address = client_params[:shipping_address]
    @client.contract_status = ContractStatus.find_by(id: client_params[:contract_status])

    if @client.save
      flash[:notice] = I18n.t('client.success.updated')
      path = clients_path
    else
      flash[:alert] = @client.errors.full_messages
      path = edit_client_path(@client)
    end

    redirect_to path
  end

  private
  def client_params
    params.permit(:id, :fio, :phone, :email, :contract, :payer, :description, :manager, :discount, :shipping_address, :contract_status)
  end

  def find_client!
    @client = Client.find_by(id: client_params[:id])
    if @client.nil?
      redirect_to clients_path, alert: I18n.t('client.failure.not_found')
    end
  end

end

app/controllers/admin/clients_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ClientsController < Admin::ApplicationController

  before_action :find_search!, :find_clients!, only: [:index]

  def index
    @clients = Admin::ClientsDecorator.decorate_collection(@filtered_clients)
  end

  private
  def clients_params
    params.permit(:search)
  end

  def find_clients!
    if @search.blank?
      @filtered_clients = Client.order('created_at DESC')
    else
      _search = "%#{@search}%"

      _by_params = Client.where("fio ILIKE ? or phone ilike ? or email ilike ? or contract ilike ? or description ilike ? or payer ilike ?", _search, _search, _search, _search, _search, _search).to_a
      _by_manager = Client.where(manager: User.managers.where("fio ilike ?", _search))

      @filtered_clients = [_by_params, _by_manager].flatten.uniq.sort{|c1, c2| c1.created_at <=> c2.created_at}

      flash.now[:notice] = I18n.t('client.success.found') % @filtered_clients.count
    end
  end

  def find_search!
    @search = clients_params[:search]
  end
end

app/controllers/manager/client_controller.rb
# -*- encoding : utf-8 -*-
class Manager::ClientController < Manager::ApplicationController

  before_action :find_client!, only: [:destroy, :edit, :update]

  def create
    new_client = Client.new

    new_client.fio = client_params[:fio]
    new_client.phone = client_params[:phone]
    new_client.email = client_params[:email]
    new_client.contract = client_params[:contract]
    new_client.payer = client_params[:payer]
    new_client.description = client_params[:description]
    new_client.manager = current_user
    new_client.discount = Discount.find_by(id: client_params[:discount])
    new_client.shipping_address = client_params[:shipping_address]
    new_client.contract_status = ContractStatus.find_by(id: client_params[:contract_status])

    if new_client.save
      flash[:notice] = I18n.t('client.success.created')
      path = manager_clients_path
    else
      flash[:alert] = new_client.errors.full_messages
      path = manager_new_client_path
    end

    redirect_to path
  end

  def destroy
    @client.destroy

    message = I18n.t('client.success.deleted')

    respond_to do |format|
      format.json { render json: {success: true, message: message} }
      format.html { redirect_to manager_clients_path, notice: message }
    end
  end

  def update
    @client.fio = client_params[:fio]
    @client.phone = client_params[:phone]
    @client.email = client_params[:email]
    @client.contract = client_params[:contract]
    @client.payer = client_params[:payer]
    @client.description = client_params[:description]
    @client.discount = Discount.find_by(id: client_params[:discount])
    @client.shipping_address = client_params[:shipping_address]
    @client.contract_status = ContractStatus.find_by(id: client_params[:contract_status])

    if @client.save
      success = true
      message = I18n.t('client.success.updated')
    else
      success = false
      message = @client.errors.full_messages
    end

    respond_to do |format|
      format.json { render json: {success: success, message: message} }
      format.html do

        if success
          flash[:notice] = message
          path = manager_clients_path
        else
          flash[:alert] = message
          path = manager_edit_client_path(@client)
        end

        redirect_to path
      end
    end
  end

  private
  def client_params
    params.permit(:id, :fio, :phone, :email, :contract, :payer, :description, :discount, :shipping_address, :contract_status)
  end

  def find_client!
    @client = Client.find_by(id: client_params[:id], manager: current_user)
    if @client.nil?
      redirect_to manager_clients_path, alert: I18n.t('client.failure.not_found')
    end
  end

end

app/controllers/manager/clients_controller.rb
# -*- encoding : utf-8 -*-
class Manager::ClientsController < Manager::ApplicationController

  def index
    @clients = Manager::ClientsDecorator.decorate_collection(current_user.clients.order(:fio))
  end

end

app/helpers/clients_helper.rb
# -*- encoding : utf-8 -*-
module ClientsHelper
end

app/views/admin/client/edit.html.erb
<%= form_for :client, :url => update_client_path(@client), :method => :post, :html => {:class => "form-validation"} do |f| %>

    <div class="bg-light lter b-b wrapper-md hidden-print">
      <%= render partial: 'shared/form_top_panel', locals: {header: t('client.edit'), button: t('client.save')} %>
    </div>

    <%= render :partial => 'layouts/flash' %>

    <div class="wrapper-md">
      <div class="row">

        <div class="col-lg-12">

          <div class="form-group">
            <label><%= t('client.fio') %></label>
            <input type="text" class="form-control" name="fio" required="" value="<%= @client.fio %>">
          </div>

          <div class="form-group">
            <label><%= t('client.phone') %></label>
            <input type="text" class="form-control" name="phone" value="<%= @client.phone %>">
          </div>

          <div class="form-group">
            <label><%= t('client.email') %></label>
            <input type="text" class="form-control" name="email" value="<%= @client.email %>">
          </div>

          <div class="form-group">
            <label><%= t('client.contract') %></label>
            <input type="text" class="form-control" name="contract" value="<%= @client.contract %>">
          </div>

          <div class="form-group">
            <label><%= t('client.payer') %></label>
            <input type="text" class="form-control" name="payer" value="<%= @client.payer %>">
          </div>

          <div class="form-group">
            <label><%= t('client.manager') %></label>
            <%= select "manager", "manager", User.managers.collect { |p| [p.fio, p.id] }, {selected: @client.manager.id}, {:class => "form-control", name: 'manager'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.discount') %></label>
            <%= select "discount", "discount", Discount.all.collect { |p| [p.name, p.id] }, {selected: @client.discount.id}, {:class => "form-control", name: 'discount'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.shipping_address') %></label>
            <input type="text" class="form-control" name="shipping_address" value="<%= @client.shipping_address %>">
          </div>

          <div class="form-group">
            <label><%= t('client.contract_status') %></label>
            <%= select "contract_status", "contract_status", ContractStatus.all.collect { |p| [p.name, p.id] }, {selected: @client.contract_status.id}, {class: "form-control", name: 'contract_status'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.description') %></label>
            <textarea class="form-control" rows="6" placeholder="<%= t('client.description') %>" name="description"><%= @client.description %></textarea>
          </div>

        </div>

      </div>
    </div>
<% end %>

app/views/admin/client/new.html.erb
<%= form_for :client, :url => create_client_path, :method => :post, :html => {:class => "form-validation"} do |f| %>

    <div class="bg-light lter b-b wrapper-md hidden-print">
      <%= render partial: 'shared/form_top_panel', locals: {header: t('client.new'), button: t('client.create')} %>
    </div>

    <%= render :partial => 'layouts/flash' %>

    <div class="wrapper-md">
      <div class="row">

        <div class="col-lg-12">

          <div class="form-group">
            <label><%= t('client.fio') %></label>
            <input type="text" class="form-control" name="fio" required="">
          </div>

          <div class="form-group">
            <label><%= t('client.phone') %></label>
            <input type="text" class="form-control" name="phone">
          </div>

          <div class="form-group">
            <label><%= t('client.email') %></label>
            <input type="text" class="form-control" name="email">
          </div>

          <div class="form-group">
            <label><%= t('client.contract') %></label>
            <input type="text" class="form-control" name="contract">
          </div>

          <div class="form-group">
            <label><%= t('client.payer') %></label>
            <input type="text" class="form-control" name="payer">
          </div>

          <div class="form-group">
            <label><%= t('client.manager') %></label>
            <%= select "manager", "manager", User.managers.collect { |p| [p.fio, p.id] }, {}, {:class => "form-control", name: 'manager'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.discount') %></label>
            <%= select "discount", "discount", Discount.all.collect { |p| [p.name, p.id] }, {}, {:class => "form-control", name: 'discount'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.shipping_address') %></label>
            <input type="text" class="form-control" name="shipping_address">
          </div>

          <div class="form-group">
            <label><%= t('client.contract_status') %></label>
            <%= select "contract_status", "contract_status", ContractStatus.all.collect { |p| [p.name, p.id] }, {}, {:class => "form-control", name: 'contract_status'} %>
          </div>

          <div class="form-group">
            <label><%= t('client.description') %></label>
            <textarea class="form-control" rows="6" placeholder="<%= t('client.description') %>" name="description"></textarea>
          </div>

        </div>
      </div>
    </div>
<% end %>